Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -49,19 +49,19 @@ jobs:
           echo "Converted JSON Array:$PYTHON_VERSIONS"
           echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_ENV
 
-    - name: Install and Verify Python Versions
-      run: |
-          sudo apt-get update
-          sudo apt-get install -y software-properties-common
-          sudo add-apt-repository -y ppa:deadsnakes/ppa
-          sudo apt-get update
-          for version in $(echo $PYTHON_VERSIONS | jq -r '.[]'); do
-            echo "Installing Python $version..."
-            sudo apt-get update
-            sudo apt-get install -y python$version
-            echo "Verifying Python $version..."
-            python$version --version || echo "Failed to verify Python $version"
-          done
+    #- name: Install and Verify Python Versions
+     # run: |
+      #    sudo apt-get update
+       #   sudo apt-get install -y software-properties-common
+        #  sudo add-apt-repository -y ppa:deadsnakes/ppa
+         # sudo apt-get update
+          #for version in $(echo $PYTHON_VERSIONS | jq -r '.[]'); do
+           # echo "Installing Python $version..."
+            #sudo apt-get update
+            #sudo apt-get install -y python$version
+            #echo "Verifying Python $version..."
+            #python$version --version || echo "Failed to verify Python $version"
+          #done
 
           
     #- name: Debug JSON Output
