Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -43,11 +43,21 @@ jobs:
           echo "$PYTHON_VERSIONS"
 
           # Convert extracted versions to JSON array format
-          JSON_VERSIONS=$(echo "$PYTHON_VERSIONS" | jq -R -s 'split("\n") | map(select(length > 0))' | jq -c '.')
+          PYTHON_VERSIONS=$(echo "$PYTHON_VERSIONS" | jq -R -s 'split("\n") | map(select(length > 0))' | jq -c '.')
       
           # Print JSON array
-          echo "Converted JSON Array:$JSON_VERSIONS"
-          echo "python_versions=$JSON_VERSIONS" >> $GITHUB_ENV
+          echo "Converted JSON Array:$PYTHON_VERSIONS"
+          echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_ENV
+
+    - name: Install and Verify Python Versions
+      run: |
+          for version in $(echo $PYTHON_VERSIONS | jq -r '.[]'); do
+            echo "Installing Python $version..."
+            sudo apt-get update
+            sudo apt-get install -y python$version
+            echo "Verifying Python $version..."
+            python$version --version || echo "Failed to verify Python $version"
+          done
 
           
     #- name: Debug JSON Output
