Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -17,20 +17,20 @@ jobs:
     - name: Print pyproject.toml content
       run: cat pyproject.toml
 
-    - name: Extract Python version
-      run: |
-          PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
-          echo "Extracted Python version: $PYTHON_VERSION"
+   # - name: Extract Python version
+    #  run: |
+     #     PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
+      #    echo "Extracted Python version: $PYTHON_VERSION"
 
-    #- name: Extract all Python versions from pyproject.toml
-     # run: |
-      #    PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
-       #   if [ -z "$PYTHON_VERSIONS" ]; then
-        #    echo "Failed to extract Python versions!"
-         #   exit 1
-         # fi
-         # echo "Extracted Python versions:"
-         # echo "$PYTHON_VERSIONS"
+    - name: Extract all Python versions from pyproject.toml
+      run: |
+          PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
+          if [ -z "$PYTHON_VERSIONS" ]; then
+            echo "Failed to extract Python versions!"
+            exit 1
+          fi
+          echo "Extracted Python versions:"
+          echo "$PYTHON_VERSIONS"
 
    # - name: Install Python 3.9
     #  uses: actions/setup-python@v4
@@ -46,10 +46,10 @@ jobs:
      # run: echo "$(python -c 'import sys; print(sys.executable)')" >>$GITHUB_PATH
           # echo "Extracted Python Version:$PYTHON_VERSION"
 
-    - name: Setup Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.python_version }}
+    #- name: Setup Python
+     # uses: actions/setup-python@v4
+     # with:
+      #  python-version: ${{ env.python_version }}
 
     - name: Verify Python version
       run: python --version
