Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -17,43 +17,39 @@ jobs:
     - name: Print pyproject.toml content
       run: cat pyproject.toml
 
-   # - name: Extract Python version
-    #  run: |
-         # PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
-         # if [-z "$PYTHON_VERSIONS" ];then
-         # echo "Failed to extract Python versions"
-         # exit 1
-         # fi
-     #     echo "Extracted Python version: $PYTHON_VERSION"
-
-    - name: Extract all Python versions from pyproject.toml
+    - name: Extract Python version
       run: |
-          PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
-          if [ -z "$PYTHON_VERSIONS" ]; then
-            echo "Failed to extract Python versions!"
-            exit 1
-          fi
-          echo "Extracted Python versions:"
-          echo "$PYTHON_VERSIONS"
+          PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
+          echo "Extracted Python version: $PYTHON_VERSION"
 
-    - name: Install Python 3.9
-      uses: actions/setup-python@v4
-      with:
-        python-version: 3.9
+    #- name: Extract all Python versions from pyproject.toml
+     # run: |
+      #    PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
+       #   if [ -z "$PYTHON_VERSIONS" ]; then
+        #    echo "Failed to extract Python versions!"
+         #   exit 1
+         # fi
+         # echo "Extracted Python versions:"
+         # echo "$PYTHON_VERSIONS"
+
+   # - name: Install Python 3.9
+    #  uses: actions/setup-python@v4
+     # with:
+      #  python-version: 3.9
        
         
      # run: |
       #    PYTHON_VERSION=$(grep -oE '(?<=^python\s*=\s*")[0-9]+\.[0-9]+' pyproject.toml || echo "NOT_FOUND")
        #   echo "Extracted Python version: $PYTHON_VERSION"
 
-    - name: Force update PATH to use installed python version
-      run: echo "$(python -c 'import sys; print(sys.executable)')" >>$GITHUB_PATH
+    #- name: Force update PATH to use installed python version
+     # run: echo "$(python -c 'import sys; print(sys.executable)')" >>$GITHUB_PATH
           # echo "Extracted Python Version:$PYTHON_VERSION"
 
-   # - name: Setup Python
-   #  uses: actions/setup-python@v5
-   #   with:
-    #    python-version: ${{ env.python_version }}
+    - name: Setup Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ env.python_version }}
 
     - name: Verify Python version
       run: python --version
