Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -17,20 +17,30 @@ jobs:
     - name: Print pyproject.toml content
       run: cat pyproject.toml
 
-    - name: Extract Python version
-      run: |
-          PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
+   # - name: Extract Python version
+    #  run: |
+          PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
           if [-z "$PYTHON_VERSIONS" ];then
           echo "Failed to extract Python versions"
           exit 1
           fi
-          echo "Extracted Python version: $PYTHON_VERSION"
+     #     echo "Extracted Python version: $PYTHON_VERSION"
 
-    - name: Install Python from extracted version
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-        cache: 'pip'
+    - name: Extract all Python versions from pyproject.toml
+      run: |
+          PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
+          if [ -z "$PYTHON_VERSIONS" ]; then
+            echo "Failed to extract Python versions!"
+            exit 1
+          fi
+          echo "Extracted Python versions:"
+          echo "$PYTHON_VERSIONS"
+
+   # - name: Install Python from extracted version
+    #  uses: actions/setup-python@v4
+     # with:
+      #  python-version: ${{ env.PYTHON_VERSION }}
+       # cache: 'pip'
         
      # run: |
       #    PYTHON_VERSION=$(grep -oE '(?<=^python\s*=\s*")[0-9]+\.[0-9]+' pyproject.toml || echo "NOT_FOUND")
