Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -32,27 +32,32 @@ jobs:
       #    PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
        #   echo "Extracted Python version: $PYTHON_VERSION"
 
-    - name: Extract all Python versions from pyproject.toml
+    - name: Extract Python version
       run: |
-          PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
-          if [ -z "$PYTHON_VERSIONS" ]; then
-            echo "Failed to extract Python versions!"
-            exit 1
-          fi
-          echo "Extracted Python versions"
-          echo "$PYTHON_VERSIONS"
+          PYTHON_VERSION=$(grep -oP '(?<=python versions = ")(.*)(?=")' pyproject.toml | \ tr '||' '\n' | sort -V | tail -n1)
+          echo "Extracted Python version: $PYTHON_VERSION"
+
+   # - name: Extract all Python versions from pyproject.toml
+    #  run: |
+     #     PYTHON_VERSIONS=$(grep -oE '^python\s*=\s*".*"' pyproject.toml | grep -oE '([0-9]+\.[0-9]+(\.[0-9]+)?)')
+      #    if [ -z "$PYTHON_VERSIONS" ]; then
+       #     echo "Failed to extract Python versions!"
+        #    exit 1
+         # fi
+          #echo "Extracted Python versions"
+          #echo "$PYTHON_VERSIONS"
 
           # Convert extracted versions to JSON array format
-          PYTHON_VERSIONS=$(echo "$PYTHON_VERSIONS" | jq -R -s 'split("\n") | map(select(length > 0))' | jq -c '.')
+          #PYTHON_VERSIONS=$(echo "$PYTHON_VERSIONS" | jq -R -s 'split("\n") | map(select(length > 0))' | jq -c '.')
       
           # Print JSON array
-          echo "Converted JSON Array:$PYTHON_VERSIONS"
-          echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_ENV
+          #echo "Converted JSON Array:$PYTHON_VERSIONS"
+          #echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_ENV
 
-    - name: Setup python
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSIONS }}
+    #- name: Setup python
+     # uses: actions/setup-python@v4
+      #with:
+       # python-version: ${{ env.PYTHON_VERSIONS }}
           
 
     #- name: Install and Verify Python Versions
