Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,6 +20,10 @@ jobs:
     - name: Extract Python version
       run: |
           PYTHON_VERSION=$(grep -oE '^python\s*=\s*"([0-9]+\.[0-9]+)"' pyproject.toml | grep -oE '[0-9]+\.[0-9]+')
+          if [-z "$PYTHON_VERSIONS" ];then
+          echo "Failed to extract Python versions"
+          exit 1
+          fi
           echo "Extracted Python version: $PYTHON_VERSION"
 
     - name: Install Python from extracted version
